export const ALERT_INFO = "ALERT_INFO";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";

export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_OUT = "SIGN_OUT";

export const CREATE_ACCOUNT_LOADING = "CREATE_ACCOUNT_LOADING";
export const CREATE_ACCOUNT_ERROR = "CREATE_ACCOUNT_ERROR";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const FETCH_ACCOUNTS_LOADING = "FETCH_ACCOUNTS_LOADING";
export const FETCH_ACCOUNTS_ERROR = "FETCH_ACCOUNTS_ERROR";
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const FETCH_ACCOUNT_LOADING = "FETCH_ACCOUNT_LOADING";
export const FETCH_ACCOUNT_ERROR = "FETCH_ACCOUNT_ERROR";
export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const EDIT_ACCOUNT = "EDIT_ACCOUNT";

export const CREATE_TRANSACTION_LOADING = "CREATE_TRANSACTION_LOADING";
export const CREATE_TRANSACTION_ERROR = "CREATE_TRANSACTION_ERROR";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const FETCH_TRANSACTIONS_LOADING = "FETCH_TRANSACTIONS_LOADING";
export const FETCH_TRANSACTIONS_ERROR = "FETCH_TRANSACTIONS_ERROR";
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_TRANSACTION_LOADING = "FETCH_TRANSACTION_LOADING";
export const FETCH_TRANSACTION_ERROR = "FETCH_TRANSACTION_ERROR";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";
export const EDIT_TRANSACTION = "EDIT_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

export const FETCH_CURRENCIES = "FETCH_CURRENCIES";

export const FETCH_MONTH_BOARD = "FETCH_MONTH_BOARD";
